name: Deploy local encoder controller
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
jobs:
  check_code:
    name: Check Code
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup GOROOT
        run: export GOROOT=/opt/homebrew/Cellar/go/1.18.3/libexec
      - name: Run localbox-build
        run: make localbox-build
      - name: Run localbox-test-copy
        run: make localbox-test-copy